env:
  amd: true
  browser: true
  es6: true
  node: true
  jquery: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  App: true
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
settings:
  react:
    version: detect
